version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
      - release

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/rupert/google-photos-backup
    steps:
      - checkout
      - run:
          name: Download dep
          command: |
            curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o /go/bin/dep
            chmod +x /go/bin/dep
      - run:
          name: Download gox
          command: go get github.com/mitchellh/gox
      - run: dep ensure
      - run: gox -osarch "linux/arm linux/amd64 darwin/amd64" -output "build/google-photos-backup_{{.OS}}_{{.Arch}}"
      - persist_to_workspace:
          root: /go/src/github.com/rupert/google-photos-backup
          paths:
            - build
      - store_artifacts:
          path: /go/src/github.com/rupert/google-photos-backup/build
          destination: build

  release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run:
          name: Download ghr
          command: go get github.com/tcnksm/ghr
