version: 2

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/rupert/google-photos-backup
    steps:
      - checkout
      - run:
          name: Download dep
          command: |
            curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o /go/bin/dep
            chmod +x /go/bin/dep
      - run: /go/bin/dep ensure
      - run: go build
