version: 2

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Download dep
          command: |
            curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o dep
            chmod +x dep
      - run: ./dep ensure
      - run: go build
